
services:
  dlrs-sonarqube:
    image: sonarqube:latest
    container_name: dlrs-sonarqube
    restart: always
    depends_on:
      - dlrs-sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://dlrs-sonarqube-db:5432/${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    ports:
      - "9001:9000"
    volumes:
      - conf:/opt/sonarqube/conf
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs
      - temp:/opt/sonarqube/temp
    networks:
      - dlrs_network

  dlrs-sonarqube-db:
    image: postgres:latest
    container_name: dlrs-sonarqube-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql
      - db_data:/var/lib/postgresql/data
    networks:
      - dlrs_network

networks:
  dlrs_network:
    name: dlrs_network
    external: true

volumes:
  conf:
  data:
  extensions:
  logs:
  temp:
  db:
  db_data: