
services:
  dlrs-sonarqube:
    image: sonarqube:lts-community
    container_name: dlrs-sonarqube
    restart: always
    depends_on:
      - dlrs-sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://dlrs-sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    ports:
      - "9001:9000"
    volumes:
      - dlrs_sonarqube_conf:/opt/sonarqube/conf
      - dlrs_sonarqube_data:/opt/sonarqube/data
      - dlrs_sonarqube_extensions:/opt/sonarqube/extensions
      - dlrs_sonarqube_logs:/opt/sonarqube/logs
      - dlrs_sonarqube_temp:/opt/sonarqube/temp

  dlrs-sonarqube-db:
    image: postgres:13
    container_name: dlrs-sonarqube-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dlrs_sonarqube_db:/var/lib/postgresql
      - dlrs_sonarqube_db_data:/var/lib/postgresql/data

volumes:
  dlrs_sonarqube_conf:
  dlrs_sonarqube_data:
  dlrs_sonarqube_extensions:
  dlrs_sonarqube_logs:
  dlrs_sonarqube_temp:
  dlrs_sonarqube_db:
  dlrs_sonarqube_db_data: